version: '3.8'
services:
  backend:

    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - CGI_PATH=/app/ncplot7py/scripts/cgiserver.cgi
      - CGI_TIMEOUT=30
    volumes:
      - ./:/app:cached
    networks:
      - ncnet


networks:
  ncnet:
    driver: bridge
